spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  secret: your_strong_secret_key_here_at_least_32_characters_long
  expiration: 86400000

# Отключаем баннер Spring Boot для лога
spring.main.banner-mode: off